name: 'Branch Backup'
description: 'Create weekly snapshot branches with rich metadata tracking for Git repositories'
author: 'ggfevans'

branding:
  icon: 'git-branch'
  color: 'green'

inputs:
  backup-prefix:
    description: 'Prefix for backup branch names'
    required: false
    default: 'backup'

  branch-to-backup:
    description: 'Branch to create backups from'
    required: false
    default: 'main'

  github-token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}

outputs:
  backup-branch:
    description: 'Name of the created backup branch'
    value: ${{ steps.backup.outputs.branch }}

  backup-status:
    description: 'Status of backup operation (created, skipped, failed)'
    value: ${{ steps.backup.outputs.status }}

  commit-sha:
    description: 'SHA of the commit that was backed up'
    value: ${{ steps.backup.outputs.commit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch-to-backup }}
        token: ${{ inputs.github-token }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create backup branch
      id: backup
      shell: bash
      env:
        INPUT_BACKUP_PREFIX: ${{ inputs.backup-prefix }}
        INPUT_BRANCH_TO_BACKUP: ${{ inputs.branch-to-backup }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Run the main backup script
        bash "$GITHUB_ACTION_PATH/src/main.sh"
